### ISSUE TITLE
organisation repositories are not picked up?

### ISSUE THREAD

**Issue by sayanee** [webuildorg/webuild-repos#5]
E.g. Location is `Singapore`, Star > `50` https://github.com/jollygoodcode/dasherize

cc @winston

**Comment by winston** [comment]
Is it working now? 😍

**Comment by sayanee** [comment]
@winston hhmmm doesn't seem to provide an API to search by location of organisations https://developer.github.com/v3/orgs/. I'm thinking whether a static list of organisations is good. Need to investigate a little more. :thought_balloon:

**Comment by sayanee** [comment]
eh? how come i closed it? sorry it was wrongly closed :sob:

**Comment by winston** [comment]
> eh? how come i closed it? sorry it was wrongly closed

Ah haha I thought you solved it. Actually I was trying to find the code in webuild that does this. Can you point me to the file?

**Comment by winston** [comment]
Does this help? https://api.github.com/search/users?q=type:org+location:Singapore

**Comment by sayanee** [comment]
thank you @winston!

The current code that searches for repositories based on some criteria is [here](https://github.com/webuildorg/webuild-repos/blob/master/repos/index.js#L87-L105)

We also used to have static list of users features and that feature could be brought back to list organisations this time. Here's the [full code at that point of history](https://github.com/webuildsg/webuild/tree/55fdbb2778e69bac8179931cfebdcf29c03304ac), the [static file](https://github.com/webuildsg/webuild/blob/55fdbb2778e69bac8179931cfebdcf29c03304ac/repos/whitelistUsers.json) and the [relevant function that adds the static list of users to all users](https://github.com/webuildsg/webuild/blob/55fdbb2778e69bac8179931cfebdcf29c03304ac/repos/github_feed.js#L66-L78).

The functions goes like this:

``` js
function insertWhiteList(searchedUsers,whitelistUsers){

  whitelistUsers.forEach(function(whitelistUser) {
    var found = searchedUsers.filter(function(searchedUser){
        return searchedUser.login === whitelistUser.login;
      });
    if (found.length === 0) {
      //console.log("adding.. ", whitelistUser.login);
      searchedUsers.push(whitelistUser);
    }
  });
  return searchedUsers;
}
```

**Comment by sayanee** [comment]
> Does this help? https://api.github.com/search/users?q=type:org+location:Singapore

:heart_eyes: yeah we found it!! Awesome will query it with your API query now. Dynamic API query is always better for magical discovery than static.

**Comment by winston** [comment]
:bow:

**Comment by winston** [comment]
I am actually interested to see which are the local companies that are actively giving back to open source (whatever language it is). They deserve a medal. :trophy:

**Comment by sayanee** [comment]
#til thanks to @winston that there are **543** organisations contributing to open source! We must totally add them. Thank you so much!!

**Comment by sayanee** [comment]
LOL Yes more medals and chocolates :candy:

**Comment by notthetup** [comment]
:shipit:

**Comment by cheeaun** [comment]
:chocolate_bar:

**Comment by sayanee** [comment]
**Before**: 
- lesser number of total repositories with > 50 stars and updated in the last 3 months

![before](https://cloud.githubusercontent.com/assets/413879/12701700/6ded46da-c84c-11e5-8665-937ba4e3ca85.jpg)

**After**:
- more number of total repositories with > 50 stars and updated in the last 3 months
- new node added with `type` which can be a `User` or `Organization` 

![after](https://cloud.githubusercontent.com/assets/413879/12701699/6de8bcf0-c84c-11e5-875c-ab02ccb30952.jpg)

**Comment by cheeaun** [comment]
:clap: :heart_eyes:

**Comment by sayanee** [comment]
:chocolate_bar: :ship: :shipit: :candy: :trophy: Shipped to production :tada: 

![image](https://cloud.githubusercontent.com/assets/413879/12701725/416aeeb8-c84d-11e5-91ad-49b20960bf91.png)
